function plotDataAndFit( t, ydata, yfit, MaterialName )
    figure; AX = axes; hold all;
    plot( t, ydata, 'k', 'linewidth', 2);
    plot( t, yfit, 'b', 'linewidth', 2);
    set(AX, 'yscale', 'log')    
    data = figdata( 'x_name','Time','x_unit','\mus',...
                    'y_name','Norm. Photon Counts',...
                    'title',MaterialName,...
                    'AXIS',[-inf inf 1e-5 1e1],...
                    'legend',{'Measured', 'Fitted'},'legend_location','Northeast');
    figureprocess(data,AX);